ansible_user: openshift
ansible_become: True

# OpenStack Provisioning Variables
# use the "-e" option to set "openstack_ssh_public_key"
#openstack_ssh_public_key:
openstack_default_image_name: "rhel-guest-image-7.3-35.x86_64"
openstack_default_flavor: "m1.large"
openstack_external_network_name: "external"
openstack_dns_domain: "casl.example.com" 
openstack_subnet_prefix: 192.168.99
openstack_nameservers: 10.9.48.31
openstack_num_masters: 3
openstack_num_nodes: 2
openstack_num_infra: 2
dns_domain: "casl.example.com"
cluster_id: "casl.example.com"
public_dns_forwarder: 10.9.48.31
env_id: "s1-ha"
openshift_authorized_key_url: "https://raw.githubusercontent.com/rhtconsulting/rhc-ose/openshift-enterprise-3/ose3eval/ose3_public_keys"
#
docker_volume_size: "50"
docker_storage_block_device: "/dev/vdb"
#
# # Subscription Management Details
rhsm_register: True
rhsm_satellite: 'sat-b.etl.rht-labs.com'
rhsm_org: 'Emerging_Tech_Lab'
rhsm_activationkey: 'casl-latest'
rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.5-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-fast-datapath-rpms"
rhsm_password: ''

