---
- include: plays/configure_host_groups.yml

- hosts: cluster_hosts
  roles:
    - role: sync-keys
      key_url: "{{ openshift_authorized_key_url }}"

- hosts: masters
  roles:
  - { role: create_users }

