---
- hosts: cluster_hosts
  roles:
    - role: sync-keys
      key_url: "{{ openshift_authorized_key_url | default('') }}"

- hosts: masters
  roles:
  - { role: create_users }

- hosts: masters[0]
  roles:
    - openshift-applier
  when:
  - openshift_cluster_content is defined
