---
 - name: "Initialize create_users facts"
   set_fact:
     users: ''

 - name: "Take demo_user input when defined"
   set_fact:
     users: "{{ demo_users }}"
   when: demo_users is defined

 - include: create_users.yml  
   static: no
   when: False


