---

- name: "Create/Apply OpenShift Cluster Content ('{{ entry.object }}') - based on individual files"
  include_tasks: process-one-entry.yml
  with_items:
  - "{{ entry.content | default([]) }}"

- name: "Apply OpenShift Cluster Content ('{{ entry.object }}') - based on directory"
  block:
  - fail:
      msg: "This functionality is being deprecated. Please use the 'content.file' variable instead. See role docs for more info."
  - command: >
      oc apply -f {{ tmp_inv_dir }}{{ entry.content_dir }}
  when:
  - entry.content_dir is defined
  - entry.content_dir|trim != ''
