version: '2'
services:
  control-host:
    command: daemonize
    volumes:
    - $SRC_CODE_DIR:$DST_CODE_DIR
    - $SRC_SSH_DIR:$DST_SSH_DIR
    - $SRC_OSP_CONFIG_DIR:$DST_OSP_CONFIG_DIR
    - $SRC_ANSIBLE_CFG:$DST_ANSIBLE_CFG
    image: redhatcop/control-host-openstack
